#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dragonbox
Version  : 1.1.3
Release  : 1
URL      : https://github.com/jk-jeon/dragonbox/archive/refs/tags/1.1.3.tar.gz
Source0  : https://github.com/jk-jeon/dragonbox/archive/refs/tags/1.1.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause BSL-1.0
Requires: dragonbox-license = %{version}-%{release}
BuildRequires : buildreq-cmake

%description
# Dragonbox
This library is a reference implementation of [Dragonbox](other_files/Dragonbox.pdf) in C++.

%package dev
Summary: dev components for the dragonbox package.
Group: Development
Provides: dragonbox-devel = %{version}-%{release}
Requires: dragonbox = %{version}-%{release}

%description dev
dev components for the dragonbox package.


%package license
Summary: license components for the dragonbox package.
Group: Default

%description license
license components for the dragonbox package.


%prep
%setup -q -n dragonbox-1.1.3
cd %{_builddir}/dragonbox-1.1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1666292117
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1666292117
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dragonbox
cp %{_builddir}/dragonbox-%{version}/LICENSE-Apache2-LLVM %{buildroot}/usr/share/package-licenses/dragonbox/76cdb6c64722fbcd432e868ee1498e304e967204
cp %{_builddir}/dragonbox-%{version}/LICENSE-Boost %{buildroot}/usr/share/package-licenses/dragonbox/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
cp %{_builddir}/dragonbox-%{version}/subproject/3rdparty/shaded_plots/license.txt %{buildroot}/usr/share/package-licenses/dragonbox/f8a98805957aaeb31ccbcf41b49bcf335d070b92
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/dragonbox-1.1.3/dragonbox/dragonbox.h
/usr/include/dragonbox-1.1.3/dragonbox/dragonbox_to_chars.h
/usr/lib64/cmake/dragonbox-1.1.3/dragonboxConfig.cmake
/usr/lib64/cmake/dragonbox-1.1.3/dragonboxConfigVersion.cmake
/usr/lib64/cmake/dragonbox-1.1.3/dragonboxTargets-relwithdebinfo.cmake
/usr/lib64/cmake/dragonbox-1.1.3/dragonboxTargets.cmake

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dragonbox/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/dragonbox/76cdb6c64722fbcd432e868ee1498e304e967204
/usr/share/package-licenses/dragonbox/f8a98805957aaeb31ccbcf41b49bcf335d070b92
